engineRevision=83675ed27633283e7fc296c8bca22e841224c096
dartVersion=3.12.2
buildMode=release
signatureActiveKeyId=dev-ed25519-v1
signatureTrustedKeys=dev-ed25519-v1:MCowBQYDK2VwAyEAOacTw2tM3un9tTOFFuSwu-3ileCIEyf16ruUnbSr3xc
signatureRevokedKeyIds=
